### ISSUE TITLE
Wayland window support in specification

### ISSUE THREAD

**Issue by sadko4u** [lv2/lv2#70]
Hi!
It seems that Wayland is extensively coming to Linux and we still have no Wayland window specification in LV2 standard but still have Gtk2 and Gtk3.
CLAP already has added support of Wayland window specification. Maybe it is also a good reason to add it to LV2? The only question is, how to deal with the case when UI supports both Wayland and X11 protocols.

**Comment by drobilla** [comment]
> The only question is

If that's the only question, then it should be straightforward for someone to contribute the necessary specification, or a working prototype implementation.

Please, feel free.

**Comment by dromer** [comment]
> CLAP already has added support of Wayland window specification.

Do you mean https://github.com/free-audio/clap/blob/27f20f81dec40b930d79ef429fd35dcc2d45db5b/include/clap/ext/gui.h#L62 ?

This is the only reference to Wayland in the CLAP API. One can hardly call this "support" though.

**Comment by sadko4u** [comment]
Yes, exactly. The problem is, the LV2 standard has many [https://lv2plug.in/ns/extensions/ui#UI](UI specifications) like [https://lv2plug.in/ns/extensions/ui#CocoaUI](CocoaUI), [https://lv2plug.in/ns/extensions/ui#X11UI](X11UI) and [https://lv2plug.in/ns/extensions/ui#WindowsUI](WindowsUI) but has nothing to deal with Wayland protocol.
Since Wayland is targeted to replace X11, I think it is a good reason to add `WaylandUI` or something similar to the specification.

**Comment by falkTX** [comment]
There are some Wayland-UI related efforts for VST3 in progress by Presonous developers, which recently released their DAW for Linux that requires using Wayland (and thus uses Wayland UI only plugins)
Their approach relies on pretty much proxying all events through a "proxy compositor", which I found overly complex, not scalable and honestly a bit ugly.

I don't want to see Wayland UIs go into this route, so did some investigation of my own, and I think we can have something much better and much simpler at the same time - subsurfaces.
Somewhat recently Wayland protocols accepted the use of subsurfaces, that works alike a stack of surfaces, similarly to how in X11 we can reparent Windows on top of each other.
See https://wayland-book.com/surfaces-in-depth/subsurfaces.html
It was not originally designed with the usecase of audio plugin UIs in mind, but honestly I think it fits pretty well.

I have been doing tests with LV2 and Wayland in https://github.com/falkTX/wayland-audio-plugin-test
It has been a few days and these are my general thoughts/points/etc:
- subsurfaces fit embedding of custom UIs very well (on early checks so far)
- the host needs can pass wl_surface* (or its file descriptor) as the UI type, this work BUT:
- the host also needs to give access to the wl_display*, so that the various ids/names match and things can work in general
- we can make use of lv2 "options" feature to pass the display pointer
- would be best if we could retrieve display from the surface, so that we only need 1 value (not sure if possible with libwayland-client)
- subsurfaces can access events meant for the parent surface, which can be a little weird
- window decorations on wayland are a major PITA, but with plugin UIs we can have them require a parent which will be providing them. plugins that care about being standalones are a problem, but outside the scope of LV2
- dealing with GL context while using the same wayland display is very tricky, I need to do more tests on what could be "best practices"
- relying on current compositor/desktop supporting all required features is not the best design, but that is how wayland works so not something for LV2 to solve (so we could say LV2 plugins under wayland require a compositor that supports subsurfaces, for example)

**Comment by JohannesLorenz** [comment]
Just to add this info here, hoping it helps: We have an unfinished Lv2 UI implementation for LMMS using suil, and it works on X11, but crashes on Wayland, with segfaults like
```
#0  0x00007ffff2903372 in _XGetRequest () from /usr/lib/libX11.so.6
#1  0x00007ffff2904ea3 in XSync () from /usr/lib/libX11.so.6
#2  0x00007fffc654242a in ?? () from /usr/lib/suil-0/libsuil_x11_in_qt5.so
#3  0x0000555555904486 in suil_instance_new (host=0x55555992ea60, controller=0x555559934620, container_type_uri=0x555555929978 "http://lv2plug.in/ns/extensions/ui#Qt5UI", plugin_uri=0x555556557480 "http://gareus.org/oss/lv2/avldrums#BlondeBop", ui_uri=<optimized out>, ui_type_uri=0x55555652c180 "http://lv2plug.in/ns/extensions/ui#X11UI", ui_bundle_path=0x5555599912a0 "/usr/lib/lv2/avldrums.lv2/", ui_binary_path=0x555559a1f260 "/usr/lib/lv2/avldrums.lv2/avldrumsUI_gl.so", features=0x7fffffffa860) at lmms/src/3rdparty/suil/suil/src/instance.c:256
```
However, on Ardour, it all works. Someone suggested this issue is because our LMMS implementation places the GUI as a widget inside a Qt window, and wayland doesn't have an equivalent to XEmbed, so it cannot embed foreign windows in a parent application.
